language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm

matrix:
  fast_finish: true
  include:
    - php: 5.3.3
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.6
      env: SILEX_VERSION=1.1.*
    - php: 5.6
      env: SILEX_VERSION=1.2.*
    - php: 5.6
      env: SILEX_VERSION=1.3.*
    - php: 5.6
      env: SILEX_VERSION="2.0.x-dev as 1.3"
  allow_failures:
    - php: 7.0
    - php: nightly
    - php: hhvm
    - env: SILEX_VERSION="2.0.x-dev as 1.3"

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer selfupdate
  - composer config -g github-oauth.github.com $GITHUB_OAUTH_TOKEN
  - if [ "$SILEX_VERSION" != "" ]; then composer require "silex/silex:${SILEX_VERSION}" --no-update; fi;
  - composer update --prefer-dist $COMPOSER_FLAGS

script:
  - php vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
  - php vendor/bin/test-reporter
