language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly

env:
  - SILEX_VERSION=1.2.*

matrix:
  fast_finish: true
  include:
    - php: 5.3.3
      env: SILEX_VERSION=1.0.* COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.6
      env: SILEX_VERSION=1.0.*
    - php: 5.6
      env: SILEX_VERSION=1.1.*
    - php: 5.6
      env: SILEX_VERSION=1.2.*
    - php: 5.6
      env: SILEX_VERSION=1.3.*@dev
  allow_failures:
    - php: hhvm
    - php: nightly
    - env: SILEX_VERSION=1.3.*@dev

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer selfupdate
  - composer config -g github-oauth.github.com $GITHUB_OAUTH_TOKEN
  - composer require "silex/silex:${SILEX_VERSION}" --no-update
  - composer update --prefer-dist $COMPOSER_FLAGS

script:
  - php vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
  - php vendor/bin/test-reporter
